# Generated by Django 5.2.5 on 2025-12-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(max_length=10),
        ),
    ]
