# Generated by Django 5.2.5 on 2025-12-03 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='timeEnd',
            new_name='time_end',
        ),
        migrations.AlterField(
            model_name='programapplication',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='CSTracker.program'),
        ),
        migrations.AlterField(
            model_name='programapplication',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='CSTracker.studentprofile'),
        ),
        migrations.AlterField(
            model_name='programsubmissions',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='CSTracker.program'),
        ),
        migrations.AlterField(
            model_name='programsubmissions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='CSTracker.studentprofile'),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='CSTracker.program'),
        ),
        migrations.AlterField(
            model_name='servicelog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='CSTracker.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
