# Generated by Django 5.2.5 on 2025-12-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='submission_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
