# Generated by Django 5.2.5 on 2025-12-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSTracker', '0002_rename_timeend_program_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programsubmissions',
            name='course',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='programsubmissions',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='programsubmissions',
            name='emergency_contact_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='programsubmissions',
            name='emergency_contact_phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='programsubmissions',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='programsubmissions',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='programsubmissions',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='programsubmissions',
            name='year_level',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
