# Generated by Django 5.2.5 on 2025-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSTracker', '0003_programsubmissions_course_programsubmissions_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='course',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='section',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='year_level',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
