# Generated by Django 5.2.5 on 2025-12-05 12:21

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSTracker', '0004_servicelog_course_servicelog_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='program_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='time_end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='time_start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
