# Generated by Django 5.2.5 on 2025-12-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSTracker', '0005_servicelog_program_date_servicelog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='facilitator',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
